#!/bin/bash

TERMINAL_BIN="alacritty"

VOL=$(pactl get-sink-volume @DEFAULT_SINK@ 2>/dev/null | awk '/Volume/{printf "%d", $5}')
MUTE=$(pactl get-sink-mute @DEFAULT_SINK@ 2>/dev/null)

if [ "$MUTE" = "Mute: yes" ]; then
    echo "| 󰖁 ${VOL}%"
elif [[ "$VOL" -le 30 ]]; then
    echo "| 󰕿 ${VOL}%"
elif [[ "$VOL" -le 70 ]]; then
    echo "| 󰖀 ${VOL}%"
else
    echo "| 󰕾 ${VOL}%"
fi
echo ""
echo "#ea999c"

case $BLOCK_BUTTON in
    1) setsid -f "$TERMINAL_BIN" --class i3-audio -e bash -lc 'wiremix' ;;
esac
