#!/bin/bash

BAT=$(ls -d /sys/class/power_supply/BAT* 2>/dev/null | head -1)

icons=("󰁺" "󰁻" "󰁼" "󰁽" "󰁾" "󰁿" "󰂀" "󰂁" "󰂂" "󰁹")
icon_charging="󰂄"

[ ! -d "$BAT" ] && exit 0

CAPACITY=$(cat $BAT/capacity)
STATUS=$(cat $BAT/status)

idx=$(( (CAPACITY - 1) / 10 ))
[[ $idx -lt 0 ]] && idx=0
[[ $idx -gt 9 ]] && idx=9
ICON="${icons[$idx]}"

if [[ "$STATUS" == "Charging" || "$STATUS" == "Full" ]]; then
    echo "| $icon_charging ${CAPACITY}%"
    echo ""
    echo "#a6d189"
elif [[ "$CAPACITY" -le 15 ]]; then
    echo "| $ICON ${CAPACITY}%"
    echo ""
    echo "#ea999c"
elif [[ "$CAPACITY" -le 30 ]]; then
    echo "| $ICON ${CAPACITY}%"
    echo ""
    echo "#e5c890"
else
    echo "| $ICON ${CAPACITY}%"
    echo ""
    echo "#99d1db"
fi

case $BLOCK_BUTTON in
    1) setsid -f alacritty --class i3cpufreq -e sudo auto-cpufreq --monitor ;;
esac
