#!/bin/bash

TERMINAL_BIN="alacritty"

ESSID=$(iwgetid -r 2>/dev/null)

if [ -n "$ESSID" ]; then
    echo "| 󰤨 $ESSID"
    echo ""
    echo "#ffffff"
else
    echo "| 󰤭 down"
    echo ""
    echo "#737994"
fi

case $BLOCK_BUTTON in
    1) setsid -f "$TERMINAL_BIN" --class i3-wifi -e bash -lc 'rfkill unblock wifi 2>/dev/null; impala' ;;
esac
