#!/bin/bash

set -o pipefail
exec 2>> /tmp/wallpaper-set.log

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOTFILES_DIR="$(cd "$SCRIPT_DIR/../../../../" && pwd)"
DEFAULT_WALLPAPER="$DOTFILES_DIR/wallpapers/0024.jpg"
WAL_CACHE="$HOME/.cache/wal/wal"
CURRENT_LINK="$HOME/.config/i3/current-wallpaper"

# Check if --no-wal flag is passed
NO_WAL=0
if [[ "$1" == "--no-wal" ]]; then
  NO_WAL=1
  shift
fi

if [[ -n $1 ]]; then
  WALLPAPER="$(realpath "$1")"
elif [[ -f "$WAL_CACHE" ]]; then
  WALLPAPER=$(cat "$WAL_CACHE")
  [[ ! -f "$WALLPAPER" ]] && WALLPAPER="$DEFAULT_WALLPAPER"
else
  WALLPAPER="$DEFAULT_WALLPAPER"
fi

if [[ ! -f "$WALLPAPER" ]]; then
  echo "File does not exist: $WALLPAPER" >&2
  read -p "Press enter to continue..."
  exit 1
fi

mkdir -p "$(dirname "$CURRENT_LINK")"
ln -nsf "$WALLPAPER" "$CURRENT_LINK"
feh --bg-scale "$WALLPAPER"

if [[ "$NO_WAL" == "0" ]] && command -v wal >/dev/null 2>&1; then
  wal -q -n -i "$WALLPAPER"
  if [[ -f "$HOME/.cache/wal/colors.sh" ]]; then
    source "$HOME/.cache/wal/colors.sh"
    FLAMESHOT_CONF="$HOME/.config/flameshot/flameshot.ini"
    [[ -f "$FLAMESHOT_CONF" ]] && sed -i "s/^drawColor=.*/drawColor=${color15}/" "$FLAMESHOT_CONF" 2>/dev/null
  fi

  # Update alacritty colors with pywal
  if [[ -f "$HOME/.cache/wal/colors.json" ]]; then
    python3 << 'PYEOF'
import json
import os
with open(os.path.expanduser('~/.cache/wal/colors.json')) as f:
    colors = json.load(f)
output = "# Generated by wal\n"
output += "[colors.primary]\n"
output += f"background = \"{colors['special']['background']}\"\n"
output += f"foreground = \"{colors['special']['foreground']}\"\n\n"
output += "[colors.cursor]\n"
output += f"background = \"{colors['special']['cursor']}\"\n"
output += f"text = \"{colors['special']['background']}\"\n\n"
output += "[colors.normal]\n"
names = ['black', 'red', 'green', 'yellow', 'blue', 'magenta', 'cyan', 'white']
for i in range(8):
    output += f"{names[i]} = \"{colors['colors'][f'color{i}']}\"\n"
output += "\n[colors.bright]\n"
for i in range(8):
    output += f"{names[i]} = \"{colors['colors'][f'color{i+8}']}\"\n"
with open(os.path.expanduser('~/.config/alacritty/alacritty-wal.toml'), 'w') as f:
    f.write(output)
PYEOF
  fi

  # Update dunst colors with pywal
  if [[ -f "$HOME/.config/dunst/generate-from-pywal.sh" ]]; then
    bash "$HOME/.config/dunst/generate-from-pywal.sh"
  fi

  # Kill rofi so it picks up new pywal colors
  pkill -9 rofi 2>/dev/null || true
fi

if [[ -f "$HOME/.cache/wal/colors.Xresources" ]] && command -v xrdb >/dev/null 2>&1; then
  xrdb -merge "$HOME/.cache/wal/colors.Xresources"
fi

