[General]
copyPathAfterSave=false
disabledTrayIcon=true
drawColor=#ff0000
drawThickness=2
saveAfterCopy=true
; savePath=/home/sohaib/Pictures
savePathFixed=true
showHelp=false
showMagnifier=false
showStartupLaunchMessage=false
uiColor=#005577
