return {
  "epwalsh/obsidian.nvim",
  version = "*",
  lazy = true,
  ft = "markdown",
  cmd = {
    "ObsidianBacklinks",
    "ObsidianDailies",
    "ObsidianFollowLink",
    "ObsidianLink",
    "ObsidianLinkNew",
    "ObsidianLinks",
    "ObsidianNew",
    "ObsidianNewFromTemplate",
    "ObsidianOpen",
    "ObsidianPasteImg",
    "ObsidianQuickSwitch",
    "ObsidianRename",
    "ObsidianSearch",
    "ObsidianTags",
    "ObsidianTemplate",
    "ObsidianToday",
    "ObsidianToggleCheckbox",
    "ObsidianTomorrow",
    "ObsidianTOC",
    "ObsidianYesterday",
  },
  keys = {
    { "<leader>ob", "<cmd>ObsidianBacklinks<CR>",   desc = "Obsidian backlinks" },
    { "<leader>od", "<cmd>ObsidianToday<CR>",       desc = "Obsidian daily note" },
    { "<leader>ol", "<cmd>ObsidianLinks<CR>",       desc = "Obsidian note links" },
    { "<leader>oo", "<cmd>ObsidianOpen<CR>",        desc = "Open current note in Obsidian app" },
    { "<leader>oq", "<cmd>ObsidianQuickSwitch<CR>", desc = "Obsidian quick switch" },
    { "<leader>os", "<cmd>ObsidianSearch<CR>",      desc = "Search Obsidian notes" },
    { "<leader>ot", "<cmd>ObsidianTemplate<CR>",    desc = "Insert Obsidian template" },
    { "<leader>oT", "<cmd>ObsidianTOC<CR>",         desc = "Obsidian table of contents" },
    { "<leader>on", "<cmd>ObsidianNew<CR>",         desc = "New Obsidian note" },
    { "<leader>op", "<cmd>ObsidianPasteImg<CR>",    desc = "Paste image into note" },
  },
  dependencies = {
    "nvim-lua/plenary.nvim",
  },
  opts = {
    workspaces = {
      {
        name = "work",
        path = vim.fn.expand("~/Work/Notes/Obsidian Vault"),
      },
      {
        name = "dropbox",
        path = vim.fn.expand("~/Dropbox/Notes/Obsidian Vault"),
      },
    },
    completion = {
      nvim_cmp = false,
      min_chars = 2,
    },
    daily_notes = {
      folder = "daily",
      date_format = "%Y-%m-%d",
    },
    new_notes_location = "current_dir",
    picker = { name = "snacks.pick" },
    ui = { enable = false },
  },
}
